---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- ANY PACKAGES USED HERE MUST BE LOADED IN THE DESCRIPTION FILE AS WELL !-->

Load the library

```{r}
library(eventsObserveR)
```

There are a set of sample event observations provided in the library

```{r}
head(sample_events_data)
```

These can be displayed in an `eventsObserver` viewer by specifying just the `place.key` as the column name "station". Unique places are distributed round a circle in the order that they first appear in the `place.key` column.

```{r}
eventsObserveR(events = sample_events_data,
               place.key = "station")
```

# Events occur at specific coordinates



```{r}
head(sample_locations_data)
```


scdsds


```{r}
eventsObserveR(events = sample_events_data, 
               place.key = "station",
               places = sample_locations_data,
               legend = legend.df,
               legend.columns = 2,
               shape.type = "circle",
               # event.radius = 10,
               size = list(
                 view.width = 1040,
                 view.height = 720,
                 interface.width = 1200, 
                 interface.height = 900))
```



```{r}
eventsObserveR(events = sample_events_data, 
               place.key = "station",
               places = sample_locations_data,
               legend = legend.df,
               legend.columns = 2,
               shape.type = "circle",
               # event.radius = 10,
               size = list(
                 view.width = 1040,
                 view.height = 720,
                 interface.width = 1200, 
                 interface.height = 900))
```


```{r}
legend.df <- sample_events_data %>%
  select(species, color) %>%
  rename(description = species) %>%
  unique()


# sample_events_data <- sample_events_data %>%
#   select(-radius)

small_events_data <- sample_events_data[1:10,]
# legend.df <- small_events_data %>%
#   select(species, color) %>%
#   rename(description = species) %>%
#   unique()

small_events_data$color[small_events_data$species == "spider"] <- "red"

new.legend.df <- data.frame(
  description = c("spider","eagle owl"),
  color = c("red", "blue")
)

eventsObserveR(events = sample_events_data, 
               place.key = "station",
               places = sample_locations_data,
               legend = legend.df,
               legend.columns = 2,
               shape.type = "circle",
               # event.radius = 10,
               size = list(
                 view.width = 1040,
                 view.height = 720,
                 interface.width = 1200, 
                 interface.height = 900))
```

